# Generated by Django 5.2.17 on 2026-09-23 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('district', models.CharField(default='Mandi', max_length=120)),
                ('state', models.CharField(default='Himachal Pradesh', max_length=120)),
                ('location_type', models.CharField(default='VILLAGE', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.PositiveIntegerField(default=0)),
                ('current_risk', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY HIGH', 'Very high'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_risk', 'name'],
                'indexes': [models.Index(fields=['district', 'name'], name='core_locati_distric_0ec23f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='MODERATE', max_length=20)),
                ('status', models.CharField(default='UNVERIFIED', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='incidents/%Y/%m/')),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('ADVISORY', 'Advisory'), ('WATCH', 'Watch'), ('WARNING', 'Warning'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('event_type', models.CharField(max_length=60)),
                ('probability', models.FloatField(default=0)),
                ('lead_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.location')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='RF-2.4.1', max_length=80)),
                ('landslide_probability', models.FloatField(default=0)),
                ('flood_probability', models.FloatField(default=0)),
                ('combined_risk', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('estimated_lead_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('factors', models.JSONField(blank=True, default=list)),
                ('forecast', models.JSONField(blank=True, default=list)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.location')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('sensor_type', models.CharField(max_length=60)),
                ('status', models.CharField(default='ONLINE', max_length=20)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=128)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('address', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=80)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('rainfall_1h', models.FloatField(default=0)),
                ('rainfall_3h', models.FloatField(default=0)),
                ('rainfall_24h', models.FloatField(default=0)),
                ('soil_moisture', models.FloatField(default=0)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('river_level', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='simulated', max_length=120)),
                ('is_validated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.location')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['location', '-observed_at'], name='core_enviro_locatio_07c0c4_idx')],
            },
        ),
    ]
